### ISSUE TITLE
Ability to register a listener for all ChromaSDK calls

### ISSUE THREAD

**Issue by njbmartin** [chroma-sdk/Colore#144]
I can see a number of use cases where registering a listener for ChromaSDK events would be useful.

i.e. Determining when the last call was in order to uninit the SDK if unused for a certain period of time

Thus it would be useful for an application to register as a listener, perhaps receiving the event and status each time a call is made to the SDK.

I will play around with this myself and update this.

**Comment by Sharparam** [comment]
Removing milestone on this, as it's quite a big change and should probably live on its own.

**Comment by Sharparam** [comment]
Closing this, at least for now. The use case of "uninit after some period of inactivity" I think would be better handled by the application or game, rather than a responsibility of Colore.

If further work is done on this, feel free to re-open.
