### ISSUE TITLE
New Keyboard Grid: Language specific Layout not working correctly

### ISSUE THREAD

**Issue by WolfspiritM** [chroma-sdk/Colore#168]
On a German Keyboard compared to the US one Key Z and Key Y are replaced.
This is not represented in the SDK it seems:
When setting Key.Z the actual key that is lighting up is "Y".
When setting Key.Y the actual key that is lighting up is "Z".

I assume this is an SDK issue as setting Key.Z from C++ does the same.
Might need some clarification from Razer to find out if Language specific Keyboard Layouts are actually supported by this as I thought this should fix the issue and should make Key.Z light up depending on the Keyboard layout.

**Comment by brandonscott** [comment]
This should definitely fix the issue.  Did you reach out to Mark on this?

**Comment by WolfspiritM** [comment]
I have not reached out to Mark yet.
I'll send him a mail later today about this issue.

**Comment by Sharparam** [comment]
The layout functionality is implemented correctly on our end, so I'll remove this from the 5.0 milestone and keep the issue open for tracking a fix on the SDK side.

**Comment by WolfspiritM** [comment]
Maybe something is broken on my Blade Stealth (US Layout) but the Grid is acting strange there, too...
When I try to light up "M" no matter if via Colore or SDK itself the "," key lights up for example.
Any many other Keys are just shifted to the left...

What the heck is going on here?

**Comment by WolfspiritM** [comment]
After talking with Razer it seems the misaligned Grid for the Blade Stealth will be fixed with an upcoming SDK release. This will not fix the Layout specific Keyboard Layouts! According to Razer this is nothing that the new Grid would have addressed anyway. Seems like this was a misinformation/misunderstanding.

KEY_Z will light up the same position on a German and English Keyboard even so it's not the Z Key on the german one. There is (as far as I can see) no different to the old API when it comes to the Blackwidow.

So I think once the SDK fixed the blade grid issue, this Issue can be closed.

**Comment by njbmartin** [comment]
Is this still present?

**Comment by WolfspiritM** [comment]
There are some Keys like OemSlash which are still not at the correct position (which is understandable cause of the Oem prefix), but for German layout at least Z and Y is switched now.

According to the release notes the Blade Grid issue is fixed, too.
I however didn't get a chance to test this yet.

**Comment by gun95** [comment]
i have blackwindow v2 (azerty) and i have the same problem whit 'M' and ','

**Comment by Sharparam** [comment]
I'll close this due to inactivity. Feel free to re-open if this is still an issue that can be derived from Colore.

If setting a certain key sets the wrong key on the keybaord, I'd hazard a guess that the issue is in the SDK somewhere as Colore simply forwards the keys and which colors they should have to it. It's possible of course that a mapping somewhere in Colore has a bug but at the moment I'm not seeing any.
