### ISSUE TITLE
Mouse Color Changes Then goes back to currently set color in synapse.

### ISSUE THREAD

**Issue by zafric101** [chroma-sdk/Colore#248]
Mouse is Razer NagaHex V2.

Everything else changes and stays (Keyboard, base stand, and mousepad)

Its like a little flicker.

Mouse.Instance.SetAll(ColoreColor.Blue); or Chroma.Instance.SetAll(ColoreColor.Blue); is my code

ive tried with both 6.0 and 5.2 on 6.0 it doesnt even give a flicker

**Comment by Sharparam** [comment]
Do you have a code example to reproduce this? It sounds as if the SDK is initializing and then immediately uninitializing afterwards.

**Comment by zafric101** [comment]
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Corale.Colore.Core;
using ColoreColor = Corale.Colore.Core.Color;
using Corale.Colore.Razer.Mouse;
using MousepadCustom = Corale.Colore.Razer.Mousepad.Effects.Wave;
namespace WindowsFormsApp2
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            timer1.Enabled = true;
            timer1.Interval = 1000;
            Chroma.Instance.SetAll(ColoreColor.Red);
        }
}

I figured a small work around i had to set the default color to transparent for some reason.

**Comment by Sharparam** [comment]
Running the same code I'm unable to reproduce it on my end. Which .NET Framework version are you building with (I was testing with 4.7.1, but anything 3.5 or higher should work fine with Colore 5.2.0)?

Also, I see some code referencing a timer in your code, what does the timer event do?

When you say "set the default color to transparent", what do you mean? Colore's colors do not have transparency.

**Comment by zafric101** [comment]
The timer is just checking a website for a string and if the string == "blue" itd set it to blue with the same code: Chroma.Instance.SetAll(ColoreColor.Red);

And by transparent i mean if i set it like that in the razer synapse app.

I was testing on 4.6.1 ill try 4.7.1

**Comment by Sharparam** [comment]
What version of Synapse are you using? And also the SDK version.

You can get the SDK version by putting the following in your `Form1_Load` method and checking the "Debug" output window in Visual Studio:

```
Console.WriteLine(Chroma.Instance.SdkVersion);
```

**Comment by permissionBRICK** [comment]
Hi, i am experiencing a similar issue, my default Synapse setting was Spectrum Cycling, and when i would initialize the sdk and set all to black, the color would just get stuck at the current cycling color unil i called uninitialize.
Chroma.Instance.Initialize();
                    Chroma.Instance.Register(this.Handle);
                    Chroma.Instance.SetAll(Color.Black);
in an earlier version of synapse i worked around that by calling setall twice in a row, but it seems the current version does not accept this.
 I managed to work around this issue again by placing a 1sec delay between the initialize&register calls and the SetAll call.

**Comment by Sharparam** [comment]
@permissionBRICK Does it make any difference if you don't call `Register`?

I'm wondering if this could be due to some throttling thing, but as far as I know the SDK should take care of that internally.

**Comment by Sharparam** [comment]
Closing due to lack of response.
