### ISSUE TITLE
razer ornata chroma not supported

### ISSUE THREAD

**Issue by lazydoorknob** [chroma-sdk/Colore#254]
its not in the "select your keyboard" option but when i choose the razer blackwidow x it kinda works but only partly. it doesnt even show the light layers that should appear in game.
![aurora](https://user-images.githubusercontent.com/47124575/51868908-34223380-2360-11e9-807d-aae513e4934e.PNG)

**Comment by Sharparam** [comment]
The Razer SDK doesn't differ between the Ornata and other keyboards as far as I'm aware (only the Deathstalker and Blade keyboards are special). Have you checked with the developer of Aurora?

**Comment by Sharparam** [comment]
Closing this due to lack of response.
