### ISSUE TITLE
REST API returns invalid status code on error

### ISSUE THREAD

**Issue by Sharparam** [chroma-sdk/Colore#258]
(Split from #257)

When doing the initialization call on the Chroma SDK with synapse/SDK 3.0 installed, the endpoint returns a list of supported devices and a result code instead of the expected session ID and endpoint URL as returned in 2.0.

It is not certain whether this is an intended breaking change or not. Awaiting official response from Razer staff.

Initial response from Razer is that this is indicative of an error (sending the wrong list of devices to `initialize`). Why an error is returning a successful `200 OK` status is unknown. Awaiting further response from Razer.

**Comment by Sharparam** [comment]
@guidoarkesteijn What is the HTTP status code that is returned when you make the calls to SDK v3?

**Comment by guidoarkesteijn** [comment]
![image](https://user-images.githubusercontent.com/8818587/54158292-7738f180-444a-11e9-91d9-545015ac8a64.png)

The HTTP status code I get back is OK on the _**/razer/chromasdk**_ endpoint in the file: _RestApi.cs_ Line: 117

**Comment by Sharparam** [comment]
Ok, I'm awaiting response from Razer on whether the `200 OK` status is to be expected even on SDK errors. If it is, then that violates every kind of REST rule ever made, and we'll have to add special handling to detect actual errors.

**Comment by Sharparam** [comment]
@guidoarkesteijn v6.0.0-rc5 should be available on NuGet now, can you test with that version and see if it still has issues in Synapse 3.0?

**Comment by guidoarkesteijn** [comment]
@Sharparam It is working correctly now. Thank you so much. 

Was the issue the supported devices list that had devices in it that were not supported anymore in Synapse 3.0?

**Comment by Sharparam** [comment]
@guidoarkesteijn That and the API returning weird results when the init call threw an error (all other APIs always return a result code but the init API only does so if an error occurs).
