### ISSUE TITLE
Get KeypressedEvent from Razer instead of Windows

### ISSUE THREAD

**Issue by glascake-com** [chroma-sdk/Colore#259]
Right now im using a windwos integrated interrupt to catch keyevents.
But there is a big problem and a small. 
The small one: you have to map all keys manually.
The big problem: windows can't reconize FN key, and numpad keys if numlock is OFF.

This is kind of a bummer if you'r trying to make a effect that is activated by keys.

Would be nice, if there was Razer interrupt where you find out wich key is physically pressed.

**Comment by njbmartin** [comment]
This is not possible, sorry.

**Comment by glascake-com** [comment]
@njbmartin  how does the razer software do it? is there another way in windows?

**Comment by Sharparam** [comment]
The Fn-key is likely handled on firmware level and never leaves the keyboard. If numlock is off then as far as Windows is concerned the keys being pressed are the same as their respective non-numpad keys (home, page up, page down, et.c.).

For now the only way to capture keys is the existing methods on Windows used by any application that needs to capture/listen to key events. As Razer doesn't expose their own internal key listener there is no way to capture key events that are internal to the firmware.
