### ISSUE TITLE
Failed to dynamically load ChromaSDK

### ISSUE THREAD

**Issue by leonardoInf** [chroma-sdk/Colore#263]
That's what I get when instantiating IChroma (i.e. trying to access the ChromaSDK. 
I have already installed Synapse 3. Do I need to copy something to some directory? Where is the CHromaSDk located anyway in a standard Synapse3 installation?

***Edit:*** At least I have found out which file is causing the error. It is https://github.com/chroma-sdk/Colore/blob/release/6.0.0/src/Colore/Native/NativeSdkMethods.cs.

**Comment by leonardoInf** [comment]
**Big News:** You can still download the SDK without Synapse: https://assets.razerzone.com/dev_portal/downloads/Razer_Chroma_SDK_Core_v1.10.6.exe

**Comment by Sharparam** [comment]
If you run the following two commands in cmd.exe, what do they output?

```
where RzChromaSDK.dll
where RzChromaSDK64.dll
```

On my system I get this:

```
C:\Users\adamh>where RzChromaSDK.dll
C:\Program Files (x86)\Razer Chroma SDK\bin\RzChromaSDK.dll

C:\Users\adamh>where RzChromaSDK64.dll
C:\Program Files\Razer Chroma SDK\bin\RzChromaSDK64.dll
C:\Windows\System32\RzChromaSDK64.dll
```

I have Synapse 2 though.

**Comment by Sharparam** [comment]
Synapse should install Chroma SDK files when you connect any Chroma-capable device, if I recall correctly. Installing the SDK without Chroma devices connected is currently not officially supported I think.

**Comment by leonardoInf** [comment]
Thanks for answering, its the same for me now, after I have additionaly downloaded the mentioned .exe. 
Before, these folders were not there, I suppose that Synapse3 has moved them or doesn't install them by default anymore.

**Comment by Sharparam** [comment]
If they moved in Synapse 3 we'll need the new paths so we know where to load them from, did you get any output from the above commands? Assuming the DLLs themselves didn't change names that is.

**Comment by leonardoInf** [comment]
The mentioned additional exe has copied them to Program Files and System32 as usual but when I remove it, the files get deleted. Simply put: The SDK was not included in my Synapse 3 instlalation and I had to manually install the SDK packages.

**Comment by Sharparam** [comment]
When you remove the installer exe the installed DLL files get deleted? That seems weird.

Do you have any Chroma devices connected?

**Comment by leonardoInf** [comment]
Xes, my keyboard. No it happens when I uninstall the additional SDK program which I had to download.

**Comment by leonardoInf** [comment]
But looking at the source code I suppose that the SDK is loaded from System32 anyway.

**Comment by Sharparam** [comment]
It will attempt to load the SDK library from any directory in the system's `PATH` variable. Synapse 2 has been adding the libraries both to System32 but also in its own directories inside program files that it adds to the `PATH`.

Unsure if Synapse 3 changed anything in this regard. I have sent a question to Razer and am waiting for a response.

**Comment by Sharparam** [comment]
@leonardoInf The response I received from Razer was:

> I assume they chose to exclude the "Chroma Connect" module while installation.
> We made it optional since January... it's selected by default during installation, but users can deselect it if they don't want to install it.

Can you confirm if you installed the "Chroma Connect" module when installing Synapse 3?

**Comment by leonardoInf** [comment]
I´m not 100 % sure, but I think that I´ve unchecked it. But AFAIK you don´t really need Synapse, because you can download the standalone SDK on their webpage.
