### ISSUE TITLE
Wiki and gh-pages not synchronized

### ISSUE THREAD

**Issue by leonardoInf** [chroma-sdk/Colore#265]
Can the gh-pages "Getting Started" and the Wiki's one be synchronized, so that they are the same without having to make a cornucopia of pull requests? And also see my pull request to make people aware of the thorough docs pages.

**Comment by Sharparam** [comment]
Not easily I don't think. It's probably better to decide on one version to keep, either the wiki or the docs page.

I think consolidating everything into the docs might be best. What we lose is the ability to quickly change the guides without having to go through the build process, but that shouldn't be too big of a problem when documentation stabilizes.

**Comment by leonardoInf** [comment]
Y, I plan to change the getting started guide a little so I suggest to leave both and maybe merge them when I consider it being done.

**Comment by leonardoInf** [comment]
As the pull request by external users dont work now, I will submit my changes to the getting started to my fork to  the gh-pages branch and your wiki. So be sure to merge them too when possible. Thx, for mainting this repo btw.

**Comment by Sharparam** [comment]
External pull requests should work now :)

And thanks for showing interest in the project! It's always nice to see new contributors popping up and it gives me some motivation to stop being lazy and get working on a proper release, heh.

**Comment by leonardoInf** [comment]
I wanted to manually merge my edits on the wiki onto gh-pages but it's a lot of work. Do you really do it by hand or is there a tool which allows you to modify the page in a "what you see is what you get" manner? Because the description says "[Automatic] Documentation Update".

**Comment by Sharparam** [comment]
Everything inside the `docs` folder in the main repo gets processed by DocFX and then automatically put into the gh-pages branch when the `develop` branch is built or a new tag is made.

You can run [DocFX](https://dotnet.github.io/docfx/) locally to preview what it would look like (install it, then open a cmd in the `docs` directory and run `docfx`).
