### ISSUE TITLE
What about REST server?

### ISSUE THREAD

**Issue by leonardoInf** [chroma-sdk/Colore#269]
I scoured the documentation and the source code to find information about the REST Api and apparently it only includes a client. Am I right that Chroma REST server is not supported by Colore?

**Comment by leonardoInf** [comment]
ok kind of a stupid question. You can find a .NET REST Server [here](https://github.com/chroma-sdk/chroma-core).

**Comment by Sharparam** [comment]
Colore has full support for using the Chroma REST API in version 6.0 (it's one of the major new features). You can create an `IChroma` instance that uses the REST API as backend with [`ColoreProvider.CreateRestAsync`](https://chroma-sdk.github.io/Colore/devdocs/api/Colore.ColoreProvider.html#Colore_ColoreProvider_CreateRestAsync_Colore_Data_AppInfo_System_Boolean_).
