### ISSUE TITLE
Color changes only in while(true)

### ISSUE THREAD

**Issue by MasterR8** [chroma-sdk/Colore#273]
I am trying to change the color of one Key on my Razer BlackWidow Chroma. Its a console application. I use .NET 4.7.2 and build for x64. This is my code:

```c#
using System;
using System.Threading.Tasks;

using Corale.Colore.Core;
using Corale.Colore.Razer.Keyboard;
using Corale.Colore.Razer.Keyboard.Effects;

namespace MicVisual
{
    class Program
    {
        static void Main(string[] args)
        {
            Chroma.Instance.Initialize();
            Console.WriteLine(Chroma.SdkAvailable);
            Console.WriteLine(Chroma.Instance.Initialized);
            Chroma.Instance.Keyboard.SetKey(Key.Backspace, Color.Red);
            Console.ReadKey();
        }
    }
}
```

When I run the Program I cant see any changes on the keyboard. when it closes, all LED's turn off and on again. the console output is:
 true
 true
For some reason it works if i place the SetKey in a while(true) loop. But it still needs a few seconds until it changes. Also every other LED is turned off in this scenario.

**Comment by Sharparam** [comment]
Is there any difference if you put a delay between setting the color and the call to `ReadKey`?

Like:

```c#
Chroma.Instance.Keyboard.SetKey(Key.Backspace, Color.Red);
System.Threading.Thread.Sleep(5000);
Console.ReadKey();
```

**Comment by MasterR8** [comment]
No there is not. Also a while true after SetKey has no impact.

**Comment by Sharparam** [comment]
Hm, what about a delay *before* the call to `SetKey`? I'm wondering if there is a small delay between the init call and the SDK actually being ready.

**Comment by MasterR8** [comment]
Very nice! That did help. Its about 1 Second you need to wait. 750ms was not enough 1000ms seems to do the trick.
