### ISSUE TITLE
New devices 

### ISSUE THREAD

**Issue by boristomas** [chroma-sdk/Colore#278]
Any updates on new device types, for example: [razer base station](https://www.razer.com/eu-en/gaming-accessories/razer-base-station-chroma)

**Comment by Sharparam** [comment]
I don't see it listed under the list of [devices supported by the Chroma SDK](https://developer.razer.com/works-with-chroma/compatible-devices/). But it'd likely be controlled via the [generic Chroma Link interface](https://assets.razerzone.com/dev_portal/C%2B%2B/html/en/namespace_chroma_s_d_k_1_1_chroma_link.html), which [Colore has support for](https://chroma-sdk.github.io/Colore/devdocs/api/Colore.IChromaLink.html).
