### ISSUE TITLE
control led strips on huntsmen elite keyboards

### ISSUE THREAD

**Issue by QuiNz0r** [chroma-sdk/Colore#281]
Can you control the huntsmen LED strips specifically? Grid didn't work for me

**Comment by Sharparam** [comment]
Looks like there a "v2" version of the custom effect for keyboards was added at some point. That might be required to support that. It's currently not exposed in Colore so we need to add that in.

**Comment by Sharparam** [comment]
Closing this for now as it should now be possible to address the LED strips with the new `ExtendedCustomKeyboardEffect` added in latest commit referenced above.

Relevant method to use it is `IKeyboard.SetExtendedCustomAsync`.
