### ISSUE TITLE
How to get mouse battery level?

### ISSUE THREAD

**Issue by JCKodel** [chroma-sdk/Colore#286]
## Detailed Description

I want to set an effect based on realtime battery level.

## Context

Since Basilisk doesn't have a battery meter and Synapse doesn't show the battery level unless I open it, I want to be able to set the color of the mouse lights or to show a system tray icon for battery level, but I couldn't get any information about the hardware itself other than colors with this sdk.

**Comment by Sharparam** [comment]
As far as I know the SDK provided by Razer does not have the capability to report battery levels of hardware. At least as far as I can gather from the [official documentation](https://assets.razerzone.com/dev_portal/C%2B%2B/html/en/index.html).
