### ISSUE TITLE
IsSdkAvailable uses wrong registry path

### ISSUE THREAD

**Issue by WolfspiritM** [chroma-sdk/Colore#288]
## Description
Since latest updates it seems like the SDK changed the path where the "Enable" flag is written to in the registry.
The old path was "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Razer Chroma SDK" the new one seems to be in the subkey "Apps".
![image](https://user-images.githubusercontent.com/5904171/118614118-b64bf580-b7bf-11eb-8dcc-149c96fe6069.png)

For old installations the Enable flag that exists doesn't get removed so it keeps working there but new installs fail

## Expected Behavior
Detect if the SDK is enabled or not

## Actual Behavior
NullReferenceException as key.GetValue("Enable") returns null

## Possible Fix
Check the new location

## Steps to Reproduce

1. Delete Registry Key
2. Repair Synapse installation
3. Call IsSdkAvailable with the native SDK

## Context

GameDog stopped working on fresh installed windows

## Your Environment

* Version of Colore used: 5 but 6 has the same issue
* SDK mode (Native or REST API): Native
* Synapse version installed: 3.6
* Chroma SDK version in use: 3.20
* Operating System and version (e.g. Windows 10 x64): Windows 10 x64
* Link to your project (if available):

**Comment by tgraupmann** [comment]
Using registry checks is not the ideal way to check for this. Instead the `Init` and `InitSDK` API should be used. A zero success result means the Chroma SDK has initialized. A non-zero result means a failure.

**Comment by Sharparam** [comment]
@tgraupmann We want to explicitly check the availability without actually initializing the SDK, though.
